### ISSUE TITLE
gcn.py报错

### ISSUE THREAD

**Issue by Pauler99** [shenweichen/GraphNeuralNetwork#4]
line 49, in <module>
    batch_size=A.shape[0], epochs=NB_EPOCH, shuffle=False, verbose=2, callbacks=[mc_callback])
line 880, in fit
    validation_steps=validation_steps)
line 329, in model_iteration
    batch_outs = f(ins_batch)
line 3061, in __call__
    dtype=tensor_type.as_numpy_dtype))
line 501, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

**Comment by shazhongcheng** [comment]
I also meet it  >_<

**Comment by lishuaibeijing0689** [comment]
gcn.py : 
[Line 72]output = tf.matmul(tf.matmul(A, features), self.kernel) # fix by ls
[Line 73]        if self.use_bias: # fix by ls
[Line 95] Adj = Input(shape=(adj_dim,)) # fix by ls

I fix the bug like this. 

@tanzhenning @shazhongcheng

**Comment by shazhongcheng** [comment]
> gcn.py :
> [Line 72]output = tf.matmul(tf.matmul(A, features), self.kernel) # fix by ls
> [Line 73] if self.use_bias: # fix by ls
> [Line 95] Adj = Input(shape=(adj_dim,)) # fix by ls
> 
> I fix the bug like this.
> 
> @tanzhenning @shazhongcheng

Which tensorflow do you use? I run on tensorflow 1.15

And follow you suggestion, I meet this:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-0ed547a9aaff> in <module>
     18 # Compile model
     19 model = GCN(A.shape[-1], feature_dim, 16, y_train.shape[1],  dropout_rate=0.5, l2_reg=2.5e-4,
---> 20             feature_less=FEATURE_LESS, )
     21 # model.compile(optimizer=Adam(0.01), loss='categorical_crossentropy',
     22 #               weighted_metrics=['categorical_crossentropy', 'acc'])

D:\Documents\Project\Python\Jupyter\机器学习\2020读书\深入浅出图神经网络\gnn\gcn.py in GCN(adj_dim, feature_dim, n_hidden, num_class, num_layers, activation, dropout_rate, l2_reg, feature_less)
    111             n_hidden = num_class
    112         print(h.shape,Adj.shape)
--> 113         h = GraphConvolution(n_hidden, activation=activation, dropout_rate=dropout_rate, l2_reg=l2_reg)([h,Adj])
    114 
    115     output = h

c:\users\sha\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    852                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    853                 else:
--> 854                   outputs = call_fn(cast_inputs, *args, **kwargs)
    855 
    856             except errors.OperatorNotAllowedInGraphError as e:

c:\users\sha\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow_core\python\autograph\impl\api.py in wrapper(*args, **kwargs)
    235       except Exception as e:  # pylint:disable=broad-except
    236         if hasattr(e, 'ag_error_metadata'):
--> 237           raise e.ag_error_metadata.to_exception(e)
    238         else:
    239           raise

AttributeError: in converted code:

    D:\Documents\Project\Python\Jupyter\机器学习\2020读书\深入浅出图神经网络\gnn\gcn.py:77 call
        act._uses_learning_phase = features._uses_learning_phase

    AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'
```

**Comment by lishuaibeijing0689** [comment]
> ```python
> AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'
> ```



> gcn.py :
> [Line 72]output = tf.matmul(tf.matmul(A, features), self.kernel) # fix by ls
> [Line 73] if self.use_bias: # fix by ls
> [Line 95] Adj = Input(shape=(adj_dim,)) # fix by ls
> 
> I fix the bug like this.
> 
> @tanzhenning @shazhongcheng



> > gcn.py :
> > [Line 72]output = tf.matmul(tf.matmul(A, features), self.kernel) # fix by ls
> > [Line 73] if self.use_bias: # fix by ls
> > [Line 95] Adj = Input(shape=(adj_dim,)) # fix by ls
> > I fix the bug like this.
> > @tanzhenning @shazhongcheng
> 
> Which tensorflow do you use? I run on tensorflow 1.15
> 
> And follow you suggestion, I meet this:
> 
> ```python
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-2-0ed547a9aaff> in <module>
>      18 # Compile model
>      19 model = GCN(A.shape[-1], feature_dim, 16, y_train.shape[1],  dropout_rate=0.5, l2_reg=2.5e-4,
> ---> 20             feature_less=FEATURE_LESS, )
>      21 # model.compile(optimizer=Adam(0.01), loss='categorical_crossentropy',
>      22 #               weighted_metrics=['categorical_crossentropy', 'acc'])
> 
> D:\Documents\Project\Python\Jupyter\机器学习\2020读书\深入浅出图神经网络\gnn\gcn.py in GCN(adj_dim, feature_dim, n_hidden, num_class, num_layers, activation, dropout_rate, l2_reg, feature_less)
>     111             n_hidden = num_class
>     112         print(h.shape,Adj.shape)
> --> 113         h = GraphConvolution(n_hidden, activation=activation, dropout_rate=dropout_rate, l2_reg=l2_reg)([h,Adj])
>     114 
>     115     output = h
> 
> c:\users\sha\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
>     852                     outputs = base_layer_utils.mark_as_return(outputs, acd)
>     853                 else:
> --> 854                   outputs = call_fn(cast_inputs, *args, **kwargs)
>     855 
>     856             except errors.OperatorNotAllowedInGraphError as e:
> 
> c:\users\sha\anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow_core\python\autograph\impl\api.py in wrapper(*args, **kwargs)
>     235       except Exception as e:  # pylint:disable=broad-except
>     236         if hasattr(e, 'ag_error_metadata'):
> --> 237           raise e.ag_error_metadata.to_exception(e)
>     238         else:
>     239           raise
> 
> AttributeError: in converted code:
> 
>     D:\Documents\Project\Python\Jupyter\机器学习\2020读书\深入浅出图神经网络\gnn\gcn.py:77 call
>         act._uses_learning_phase = features._uses_learning_phase
> 
>     AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'
> ```

I use tensorflow 1.12

**Comment by ZhangypSam** [comment]
> gcn.py :
> [Line 72]output = tf.matmul(tf.matmul(A, features), self.kernel) # fix by ls
> [Line 73] if self.use_bias: # fix by ls
> [Line 95] Adj = Input(shape=(adj_dim,)) # fix by ls
> 
> I fix the bug like this.
> 
> @tanzhenning @shazhongcheng

I follow your suggestion and it work！And I use tensorflow 1.12, too!
